# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: 'Chris'
description: 'Full-Stack .NET Developer'
meta_description: 'Personal blog of Chris Tartamella'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "My name is Chris Tartamella. I've been writing code since I was 10 and I don't intend to stop now.  I'm a full stack .NET developer based in Philadelphia, Pennsylvania."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: "https://chris.tartamella.me"
disqus: chris-tartamella-me
mailchimp_url: #'//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 'UA-82262711-1'

# Contact form setings
email: chris@tartamella.me
contact_page_description: "If I've written about something you have questions about, or you have content you'd like to see here, get in touch!"
thankyou_page_description: "Thanks for your comments.  I'll get back to you as soon as possible."

# Social links
twitter: 'voicesfordaze'
facebook: 'chris.tartamella.7'
github: 'ctartamella'
codepen:
dribbble:
medium:
instagram:
pinterest:
linkedin: 'chris-tartamella-21a8bb115'
producthunt: 
quora:

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Reflutter
    url: /reflutter
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Build settings
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: ["README.md"]